spring.application.name=backend

# Gemini via OpenAI-compatible API (GRATIS)
spring.ai.openai.api-key=AIzaSyBpkKOriQSNTS8kw6IY0MtDNEGP8lyXCrk
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-2.0-flash

# MongoDB
# LOCAL (desarrollo)
# spring.data.mongodb.uri=mongodb://localhost:27017/workflow_db

# NUBE (producción - Atlas)
spring.data.mongodb.uri=mongodb+srv://kihomyvp_db_user:Workflow2026@cluster0.2n2bv2f.mongodb.net/workflow_db
# Puerto
server.port=8080

# Reducir logs
logging.level.org.mongodb.driver=WARN
logging.level.org.springframework=WARN
logging.level.com.workflow=INFO

# JWT
jwt.secret=workflow2026SecretKeyParaJWTMuyLargaYSegura123456789
jwt.expiration=86400000